"""Generate docs/commands.md from the live command registry.

    python scripts/gen_command_docs.py          # write the file
    python scripts/gen_command_docs.py --check  # fail if it's out of date (used in CI)
"""

from __future__ import annotations

import sys
from pathlib import Path

from shtick.magics import MAGICS, ORDER

TARGET = Path(__file__).resolve().parent.parent / "docs" / "commands.md"


def render() -> str:
    groups: dict[str, list] = {}
    for name, spec in MAGICS.items():
        if name == spec.name:
            groups.setdefault(spec.category, []).append(spec)

    lines = [
        "# Command reference",
        "",
        "<!-- Generated by scripts/gen_command_docs.py — do not edit by hand. -->",
        "",
        "Commands start with `%` at the beginning of the input (a line starting with `%` is essentially never valid shell).",
        "Inside shtick, `%help name` shows the same details.",
        "",
    ]
    for category in sorted(groups, key=lambda c: ORDER.index(c) if c in ORDER else len(ORDER)):
        lines += [f"## {category[0].upper() + category[1:]}", ""]
        for spec in sorted(groups[category], key=lambda s: s.name):
            names = ", ".join(f"`%{n}`" for n in (spec.name, *spec.aliases))
            lines += [f"### {names}", "", spec.doc[0].upper() + spec.doc[1:] + "."]
            if spec.usage:
                lines += ["", "```text", spec.usage, "```"]
            lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def main() -> int:
    content = render()
    if "--check" in sys.argv:
        if not TARGET.exists() or TARGET.read_text() != content:
            print("docs/commands.md is out of date — run: python scripts/gen_command_docs.py", file=sys.stderr)
            return 1
        return 0
    TARGET.write_text(content)
    print(f"wrote {TARGET}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
